dist: bionic
language: python

python:
  - "3.7"

services:
  - docker

before_install:
  - docker run -d -p 4444:4444 -p 5900:5900 -v /dev/shm:/dev/shm selenium/standalone-chrome-debug

before_script:
  - pip install -r requirements.txt
  - python3 manage.py migrate
  - python3 manage.py runserver 172.17.0.1:8000&
  - npm install

script: npm test test/acceptance/features/

cache: pip