# Generated by Django 2.2.4 on 2019-08-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('position', models.IntegerField()),
            ],
        ),
    ]
