# Generated by Django 2.2.4 on 2019-08-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='element_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
