# Generated by Django 3.0 on 2020-04-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200412_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='position',
            field=models.IntegerField(),
        ),
    ]
